version: '3.8'

name: glpi-docker-MagSec-edition
services:
  glpi:
    build: .
    container_name: glpi-app
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - glpi_files:/var/www/html/files
      - glpi_config:/var/www/html/config
      - glpi_main:/var/www/html/
    environment:
      - TZ=Europe/Amsterdam # Set your timezone
      - DB_HOST=glpi-db # Internal hostname
      - DB_PORT=3306 # Internal port (always 3306 inside network)
    depends_on:
      - glpi-db
    networks:
      - glpi-network

  glpi-db:
    image: mysql:8.0
    container_name: glpi-db
    restart: unless-stopped
    ports:
      - '3307:3306' # Map host port 3307 to container port 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: glpi_db
      MYSQL_USER: glpi_user
      MYSQL_PASSWORD: glpi_password
      MYSQL_ROOT_HOST: '%'
    volumes:
      - glpi_mysql_data:/var/lib/mysql
      - glpi_mysql_config:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --explicit_defaults_for_timestamp=1
    networks:
      - glpi-network

volumes:
  glpi_files:
  glpi_config:
  glpi_mysql_data:
  glpi_mysql_config:
  glpi_main:

networks:
  glpi-network:
    driver: bridge
